### ISSUE TITLE
[feature] ネットワークアクセス制限 クラスの カスタムルールの実装

### ISSUE THREAD

**Issue by myosotis-dev** [TKYcraft/chisato#40]
## 概要
- ネットワークアクセス制限クラスにカスタムルールを実装したい
- イメージはネットワーク機器のACL設定

## 前提
- #39

**Comment by myosotis-dev** [comment]
メモ config のファイル形式迷う。

## 案1
allow / deny , IP address / hostname で分類した書き方
メリット:
- IPアドレスやhostnameのparseチェックが楽になる

デメリット:
- 優先順位付けが難しい
	- 10.0.0.0/16 deny の 10.0.0.1/32 allow みたいな条件が書けない

```yaml
allow:
	ipaddress:
		- 127.0.0.x
	hostname: 
		- example.com
deny:
	ipaddress:
		- 127.0.0.x
	hostname: 
		- example.com
```

## 案2
ネットワーク機器のACLのような、下の行で上の行が上書きできる仕組み

```yaml
rule: 
	- 127.0.0.1 allow
	- example.com deny
	- 10.0.0.0/16 deny
	- 10.0.0.1/32 allow   # これは許可されるイメージ
```
